import type { SubstitutionRuleSeed } from "./types";

const baseRules: SubstitutionRuleSeed[] = [
  { canonical_ingredient: "chicken breast", substitute_ingredient: "chicken thigh", quality_tier: "high", reason: "similar flavour and cooking behaviour" },
  { canonical_ingredient: "minced beef", substitute_ingredient: "turkey mince", quality_tier: "medium", reason: "leaner protein with similar texture" },
  { canonical_ingredient: "minced beef", substitute_ingredient: "pork mince", quality_tier: "medium", reason: "close mouthfeel for sauces" },
  { canonical_ingredient: "basmati rice", substitute_ingredient: "jasmine rice", quality_tier: "high", reason: "equivalent grain size and cook time" },
  { canonical_ingredient: "spaghetti", substitute_ingredient: "tagliatelle", quality_tier: "medium", reason: "similar pasta base in sauce-led meals" },
  { canonical_ingredient: "penne pasta", substitute_ingredient: "fusilli pasta", quality_tier: "high", reason: "equivalent pasta format for bakes" },
  { canonical_ingredient: "kidney beans", substitute_ingredient: "black beans", quality_tier: "high", reason: "similar use in chilli and burritos" },
  { canonical_ingredient: "kidney beans", substitute_ingredient: "butter beans", quality_tier: "medium", reason: "works in stews and soups" },
  { canonical_ingredient: "chopped tomatoes", substitute_ingredient: "passata", quality_tier: "high", reason: "tomato base can be swapped in sauces" },
  { canonical_ingredient: "semi-skimmed milk", substitute_ingredient: "natural yogurt", quality_tier: "low", reason: "adds dairy body when diluted" },
  { canonical_ingredient: "cheddar cheese", substitute_ingredient: "mozzarella", quality_tier: "medium", reason: "melting cheese alternative" },
  { canonical_ingredient: "cheddar cheese", substitute_ingredient: "parmesan", quality_tier: "low", reason: "stronger flavour but still a hard cheese" },
  { canonical_ingredient: "spinach", substitute_ingredient: "kale", quality_tier: "medium", reason: "leafy green replacement in cooked meals" },
  { canonical_ingredient: "fresh coriander", substitute_ingredient: "fresh parsley", quality_tier: "medium", reason: "fresh herb substitute for garnish" },
  { canonical_ingredient: "fresh basil", substitute_ingredient: "fresh parsley", quality_tier: "low", reason: "herb fallback when basil unavailable" },
  { canonical_ingredient: "olive oil", substitute_ingredient: "sunflower oil", quality_tier: "medium", reason: "neutral cooking oil fallback" },
  { canonical_ingredient: "coconut milk", substitute_ingredient: "double cream", quality_tier: "low", reason: "richness replacement in curry sauces" },
  { canonical_ingredient: "baking potato", substitute_ingredient: "sweet potato", quality_tier: "medium", reason: "similar baking use with sweeter profile" },
  { canonical_ingredient: "bell pepper", substitute_ingredient: "courgette", quality_tier: "medium", reason: "vegetable volume replacement in stir-fry" },
  { canonical_ingredient: "onion", substitute_ingredient: "red onion", quality_tier: "high", reason: "like-for-like aromatic base" },
];

const generatedPairs: Array<[string, string, SubstitutionRuleSeed["quality_tier"], string]> = [
  ["black beans", "cannellini beans", "medium", "alternative bean with similar protein content"],
  ["chickpeas", "butter beans", "medium", "pulse replacement in bowls and soups"],
  ["chickpeas", "cannellini beans", "medium", "similar pantry pulse for batch cooking"],
  ["garlic", "ginger", "low", "aromatic swap in stir-fry and curry"],
  ["broccoli", "green beans", "medium", "green veg substitution with close cook time"],
  ["broccoli", "cauliflower", "high", "brassica swap in traybakes and curries"],
  ["courgette", "aubergine", "medium", "soft vegetable replacement in sauces"],
  ["carrot", "parsnip", "medium", "root veg substitution for soups"],
  ["carrot", "swede", "low", "bulk root replacement in stews"],
  ["egg noodles", "spaghetti", "low", "carb base substitute where shape is flexible"],
  ["egg noodles", "fusilli pasta", "low", "starch base replacement in simple bowls"],
  ["wholemeal bread", "white bread", "high", "direct bread swap"],
  ["wholemeal bread", "pitta bread", "medium", "alternate bread carrier"],
  ["tortilla wraps", "pitta bread", "medium", "portable meal base replacement"],
  ["tortilla wraps", "naans", "low", "flatbread swap in wraps and rolls"],
  ["semi-skimmed milk", "double cream", "low", "dairy replacement with dilution"],
  ["natural yogurt", "greek yogurt", "high", "same dairy family and texture"],
  ["natural yogurt", "cottage cheese", "low", "protein-focused dairy replacement"],
  ["tuna chunks", "smoked mackerel", "medium", "fish protein replacement"],
  ["white fish fillet", "salmon fillet", "medium", "fish swap with higher fat profile"],
  ["salmon fillet", "white fish fillet", "medium", "lean fish replacement"],
  ["minced beef", "green lentils", "low", "plant-based bulk replacement"],
  ["chicken breast", "prawns", "low", "quick-cook protein replacement"],
  ["chicken breast", "halloumi", "low", "vegetarian protein substitute"],
  ["vegetable stock", "chicken stock", "high", "stock base replacement"],
  ["paprika", "smoked paprika", "high", "same spice family with smokier flavour"],
  ["ground cumin", "garam masala", "medium", "warm spice profile replacement"],
  ["curry powder", "garam masala", "medium", "curry spice replacement"],
  ["tomato puree", "passata", "medium", "tomato concentrate replacement with adjusted quantity"],
  ["passata", "chopped tomatoes", "high", "tomato sauce base replacement"],
  ["baking potato", "butternut squash", "low", "starchy vegetable replacement"],
  ["sweet potato", "butternut squash", "medium", "sweet starchy vegetable replacement"],
  ["spinach", "frozen spinach", "high", "equivalent leafy ingredient in cooked dishes"],
  ["mixed salad leaves", "romaine lettuce", "high", "fresh salad base replacement"],
  ["mixed salad leaves", "rocket", "medium", "peppery leaf substitute"],
  ["fresh parsley", "dried oregano", "low", "herb fallback when fresh unavailable"],
  ["fresh coriander", "dried oregano", "low", "herb fallback with reduced quantity"],
  ["fresh basil", "dried oregano", "low", "dried herb fallback"],
  ["peanut butter", "almond butter", "medium", "nut spread replacement"],
  ["jam", "honey", "medium", "sweet spread replacement"],
];

export const substitutionRulesSeed: SubstitutionRuleSeed[] = [
  ...baseRules,
  ...generatedPairs.map(([canonical_ingredient, substitute_ingredient, quality_tier, reason]) => ({
    canonical_ingredient,
    substitute_ingredient,
    quality_tier,
    reason,
  })),
];
